MyShop/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyShop.Models
{
    public class Product
    {
        public int id { set; get; }
        public string name { set; get; }
        public string shortDesc { set; get; }
        public string longDesc { set; get; }
        public string img { set; get; }
        public uint price { set; get; }
        public bool isFavorite { set; get; }
        public bool available { set; get; }
        public int categoryID { set; get; }
        public virtual Category Category { set; get; }
    }
}

MyShop/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using MyShop.Interfaces;
using MyShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyShop.Controllers
{
    public class MainController : Controller
    {
        private readonly IProducts _products;

        public MainController(IProducts products)
        {
            _products = products;
        }

        public ViewResult Index()
        {
            var mainProducts = new MainViewModel
            {
                favProducts = _products.GetFavProducts
            };

            return View(mainProducts);
        }
    }
}

MyShop/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using MyShop.Interfaces;
using MyShop.Models;
using MyShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyShop.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProducts _products;
        private readonly IProductsCategory _productsCategory;

        public ProductsController(IProducts products,IProductsCategory productsCategory)
        {
            _products = products;
            _productsCategory = productsCategory;
        }


        [Route("Products/List")]
        [Route("Products/List/{category?}")]
        public ViewResult List(string category)
        {
            string _category = category;

            IEnumerable<Product> products = null;
            string currCategory = "";

            if (string.IsNullOrEmpty(category))
            {
                products = _products.Products.OrderBy(i => i.id);
            }
            else
            {
                if (string.Equals("phones", category, StringComparison.OrdinalIgnoreCase))
                {
                    products = _products.Products.Where(i => i.Category.categoryName == "Мобильные телефоны").OrderBy(i => i.id);
                    currCategory = "Мобильные телефоны";
                }
                if (string.Equals("televisors", category, StringComparison.OrdinalIgnoreCase))
                {
                    products = _products.Products.Where(i => i.Category.categoryName == "Телевизоры").OrderBy(i => i.id);
                    currCategory = "Телевизоры";
                }
            }

            var prodObj = new ProductListViewModel
            {
                getAllProducts = products,
                currCategory = currCategory
            };

            return View(prodObj);
        }

        [HttpPost]
        public async Task<IActionResult> Search(string prodName)
        {
            IEnumerable<Product> products = null;
            string resultSearch = "";


            if (string.IsNullOrEmpty(prodName))
            {
                products = _products.Products.OrderBy(i => i.id);
            }
            else
            {
                products = _products.Products.Where(n => n.name.Contains(prodName));
            }
            var prodObj = new ProductListViewModel
            {
                getAllProducts = products,
                searchResult = prodName
            };
            return View(prodObj);
        }
    }
}

MyShop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using MyShop.Interfaces;
using MyShop.Models;
using MyShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyShop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IProducts _products;
        private readonly ShopCart _shopCart;

        public ShopCartController(IProducts products,ShopCart shopCart)
        {
            _products = products;
            _shopCart = shopCart;
        }

        public ViewResult Index() 
        {
            var items = _shopCart.GetShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };

            return View(obj);
        }

        public RedirectToActionResult AddToCart(int id)
        {
            var item = _products.Products.FirstOrDefault(i => i.id == id);

            if(item != null)
            {
                _shopCart.AddToCart(item);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromCart(int id)
        {
            ShopCartItem item = _shopCart.Find(id);
            _shopCart.RemoveFromCart(item);


            return RedirectToAction("Index");
        }
    }
}

MyShop/Views/Shared/Products.cshtml
@model Product

<link href="~/css/site.css" rel="stylesheet" />
<div class="col-lg-4">
    <img class="picture" src="@Model.img" alt="@Model.name"/>
    <h2>@Model.name</h2>
    <p>Цена : @Model.price</p>
    <div class="row">
        <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="AddToCart" asp-route-id="@Model.id">Добавить в корзину</a></p>
    </div>
</div>

MyShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="#">Магазин</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Main" asp-action="Index">Главная страница <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Products/List/phones">Мобильные телефоны</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Products/List/televisors">Телевизоры</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ShopCart" asp-action="Index">Корзина</a>
                    </li>

                </ul>
                <form class="form-inline mt-2 mt-md-0" asp-controller="Products" asp-action="Search">
                    <input class="form-control mr-sm-2" type="text" name="ProdName" placeholder="Поиск" aria-label="Search">
                    <input class="btn btn-outline-light my-2 my-sm-0" type="submit" value="Найти">
                </form>
                @*<form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>*@
            </div>
        </nav>
    </header>
    <div>
        <div class="container mt-5 ">
            @RenderBody()
        </div>

    </div>
    <footer class="container">
        <p class="float-right"><a asp-controller="Main" asp-action="Index">Вернуться на главную страницу</a></p>
        <p>© 2019-2020 Project for Sigma Software· <a href="#">Privacy</a> · <a href="#">Terms</a></p>
    </footer>
</body>
</html>